- id: schedule
  name: schedule commit
  description: 'schedule your commit based on allowed dates.'
  entry: schedule_pre_commit_hooks
  language: rust
  stages:
    - post-commit
  always_run: true
